graph LR
A(SCH) --> B[/Avatar/]
B --> BA[Algo]
BA --> BAA[md5]
BA --> BAB[sha1]
BA --> BAC[sha224]
BA --> BAD[sha256]
BA --> BAE[sha384]
BA --> BAF[sha512]
B --> BC[Generator]
BC --> BCA["generate_avatar()"]
A --> C[/Config/]
C --> CA[Config]
CA --> CAA["load_json()"]
CA --> CAB["load_yaml()"]
CA --> CAC["load_toml()"]
CA --> CAD["load_ini()"]
CA --> CAE["get()"]
C --> CB[ConfigConverter]
CB --> CBA["load_json()"]
CB --> CBB["load_yaml()"]
CB --> CBC["load_toml()"]
CB --> CBD["load_ini()"]
CB --> CBE["save_json()"]
CB --> CBF["save_yaml()"]
CB --> CBG["save_toml()"]
CB --> CBH["save_ini()"]
CB --> CBI["load_data()"]
CB --> CBJ["dump_data()"]
A --> D[/ImageAPI/]
A --> E[/Interval/]
A --> F[/LedControl/]
A --> G[/Logger/]
G --> GA[Logger]
GA --> GAA["info()"]
GA --> GAB["debug()"]
GA --> GAC["warning()"]
GA --> GAD["error()"]
GA --> GAE["critical()"]
G --> GB[LoggerConfig]
GB --> GBA["set_enable()"]
GB --> GBB["set_level()"]
GB --> GBC["set_format()"]
GB --> GBD["set_enable_console()"]
GB --> GBE["set_enable_file()"]
GB --> GBE["set_file_path()"]
GB --> GBF["get_enable()"]
GB --> GBG["get_level()"]
GB --> GBH["get_format()"]
GB --> GBI["get_enable_console()"]
GB --> GBJ["get_enable_file()"]
GB --> GBK["get_file_path()"]
A --> H[/MySQL/]
H --> HA[MySQL]
HA --> HAA["connect()"]
HA --> HAB["set_echo()"]
HA --> HAC["create_table()"]
HA --> HAD["fetchall()"]
HA --> HAE["fetchone()"]
HA --> HAF["select()"]
HA --> HAG["exists()"]
HA --> HAH["insert()"]
HA --> HAI["update()"]
HA --> HAJ["delete()"]
HA --> HAK["execute()"]
HA --> HAL["commit()"]
HA --> HAM["get_version()"]
HA --> HAN["get_tables()"]
HA --> HAO["table_exists()"]
HA --> HAP["drop_table()"]
H --> HB["table()"]
H --> HC[Constants]
HC --> HCA["Or()"]
HC --> HCB["And()"]
HC --> HCC["Not()"]
HC --> HCD["Null()"]
A --> I[/OpenList/]
A --> J[/S3/]
J --> JA[S3]
JA --> JAA["list_buckets()"]
JA --> JAB["set_bucket()"]
JA --> JAC["read_file()"]
JA --> JAD["write_file()"]
JA --> JAE["delete_file()"]
A --> K[/Util/]
K --> KA[Base64]
KA --> KAA["base64_encode()"]
KA --> KAB["base64_decode()"]
K --> KB[Clip]
KB --> KBA["copy_text()"]
KB --> KBB["paste_text()"]
K --> KC[Markdown]
KC --> KCA["html_to_markdown()"]
KC --> KCB["markdown_to_html()"]
K --> KD[Password]
KD --> KDA["password_hide()"]
KD --> KDB["md5()"]
KD --> KDC["generate_password()"]
KD --> KDD["uuid()"]
K --> KE[Mermaid]
KD --> KEA["render_mermaid()"]